<?php


namespace App\Repositories\Fields;

use App\Models\Notice;
use App\Repositories\BaseRepository;
use Illuminate\Support\Facades\Cache;

class NoticeRepository extends BaseRepository
{

    protected $model;

    public function __construct(Notice $notice){
        $this->model = $notice;
    }

    /**
     * 主页通知
     * @return mixed
     */
    public function getNotices(){
        if(Cache::has('notices')){
            $notices = json_decode(Cache::get('notices'));
        }else{
            $where = array(
                ['is_exist',true],
            );
            $orderBy = array(
                ['published_at','desc']
            );
            $limit = 30;
            $notices = $this->search($where,null,$orderBy,$limit);
            Cache::add('notices',json_encode($notices),120);
        }
        return $notices;
    }

    /**
     * 查询指定id通知
     * @param $id
     * @param bool $isFail
     * @return mixed
     */
    public function getById($id, $isFail = true)
    {
        return parent::getById($id, $isFail); // TODO: Change the autogenerated stub
    }

}
